In [2]:
import torch

In [29]:
t = torch.rand(4,5)

In [35]:
print(t)

tensor([[0.8085, 0.2413, 0.9503, 0.1682, 0.0903],
        [0.8085, 0.1849, 0.2273, 0.9474, 0.4653],
        [0.3121, 0.7255, 0.7392, 0.9170, 0.7604],
        [0.3451, 0.7838, 0.1670, 0.4356, 0.1761]])


In [31]:
labels = torch.tensor([2, 0, 4, 1])

In [43]:
t[0, labels]

tensor([0.9503, 0.8085, 0.0903, 0.2413])

In [44]:
t

tensor([[0.8085, 0.2413, 0.9503, 0.1682, 0.0903],
        [0.8085, 0.1849, 0.2273, 0.9474, 0.4653],
        [0.3121, 0.7255, 0.7392, 0.9170, 0.7604],
        [0.3451, 0.7838, 0.1670, 0.4356, 0.1761]])

In [52]:
pythongrid = [
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
]

In [53]:
rows = [0, 1, 2]

In [54]:
cols = [2, 0, 1]

In [56]:
import torch
t = torch.tensor(pythongrid)
print(t[rows, cols])

tensor([30, 40, 80])
